name: Check README Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check links in the README file
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: ./README.md